<?php

/**
 * @file
 * This is the module file.
 */

use Drupal\Core\Form\FormStateInterface;

function site_alter_form_views_exposed_form_alter(array &$form, FormStateInterface $form_state, $form_id) {

    if($form_id == "views_exposed_form"){

        if (isset($form['field_investment_type_target_id'])) {
                $form['field_investment_type_target_id']['#options']["All"] = 'All Investment Type';
        }
        if (isset($form['field_industry_target_id'])) {
                $form['field_industry_target_id']['#options']["All"] = 'All Industries';
        }
        if (isset($form['field_current_realized_target_id'])) {
                $form['field_current_realized_target_id']['#options']["All"] = 'Current & Realized';
        }
        if (isset($form['tid'])) {
                $form['tid']['#options']["All"] = 'All Platforms';
        }
        if (isset($form['field_platform_target_id'])) {
                $form['field_platform_target_id']['#options']["All"] = 'All Platforms';
        }
        if (isset($form['field_function_target_id'])) {
                $form['field_function_target_id']['#options']["All"] = 'All Functions';
        }
    }
  
}
