node_status_config.admin_settings_form:
  path: '/admin/config/node/adminsettings'
  defaults:
    _form: '\Drupal\node_status_config\Form\NodeConfigForm'
    _title: 'Node Status Configuration'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE